steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/tennisfriendassociationbot/tennis-tg', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/tennisfriendassociationbot/tennis-tg']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'tennis-tg', '--image', 'gcr.io/tennisfriendassociationbot/tennis-tg', '--region', 'us-west1',  '--platform', 'managed', '--port', '8080', '--container-port', '8080', '--allow-unauthenticated']
images:
- 'gcr.io/tennisfriendassociationbot/tennis-tg'
options:
  logging: CLOUD_LOGGING_ONLY
