steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/tennisfriendassociationbot/tennis-tg', '.']
  dir: '.'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/tennisfriendassociationbot/tennis-tg' ]
images:
- 'gcr.io/tennisfriendassociationbot/tennis-tg'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'tennis-tg', '--image', 'gcr.io/tennisfriendassociationbot/tennis-tg', '--region', 'us-east1', '--platform', 'managed', '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY